#!/usr/bin/env python3
"""Fix all heading formats to bilingual EN | CN in output chunks."""
import json
import re
from pathlib import Path

TEMP = Path("/Users/jianmingwang/Downloads/00_study/02_work/01_book/pcie_cxl/MindShare_PCIe_Technology_3.0_mineru_v2/MindShare_PCI_Express_Technology_3.0_temp")

# Comprehensive EN→CN heading translation map
EN2CN = {
    "2.5 GT/s": "2.5 GT/s",
    "2.5 and 5.0 GT/s": "2.5 和 5.0 GT/s",
    "5.0 GT/s": "5.0 GT/s",
    "5.0 GT/s Operation": "5.0 GT/s 操作",
    "8.0 GT/s": "8.0 GT/s",
    "8.0 GT/s Operation": "8.0 GT/s 操作",
    "A Latency Improvement Option": "延迟改善选项",
    "ACKD_SEQ Register": "ACKD_SEQ 寄存器",
    "ACPI Driver Controls Non-Standard Embedded Devices": "ACPI 驱动控制非标准嵌入式设备",
    "ACPI Spec Defines Overall PM": "ACPI 规范定义整体电源管理",
    "ARI (Alternative Routing-ID Interpretation)": "ARI（替代路由ID解读）",
    "ASPM Options": "ASPM 选项",
    "Ack/Nak Examples": "Ack/Nak 示例",
    "Ack/Nak Generator": "Ack/Nak 生成器",
    "Ack/Nak Protocol Details": "Ack/Nak 协议细节",
    "AckNak_LATENCY_TIMER": "AckNak_LATENCY_TIMER",
    "Active State Power Management (ASPM)": "主动状态电源管理（ASPM）",
    "Advanced Error Reporting (AER)": "高级错误报告（AER）",
    "Advanced Source ID Register": "高级源ID寄存器",
    "Advisory Non-Fatal Cases": "建议性非致命情况",
    "Advisory Non-Fatal Errors": "建议性非致命错误",
    "After a 2ms timeout:": "经过 2ms 超时后：",
    "Appendix: Address Translation and Host Failover": "附录：地址转换与主机故障切换",
    "Appendix: Analysis Tools and Test Equipment": "附录：分析工具与测试设备",
    "Appendix: Lock Sequence": "附录：锁定序列",
    "Appendix: Switch and Data Center Applications": "附录：交换机和数据中心应用",
    "Arbitration in Multi-Function Endpoints": "多功能端点中的仲裁",
    "Assigning TCs to each VC — TC/VC Mapping": "分配 TC 给每个 VC — TC/VC 映射",
    "Associating the INTx# Line to an IRQ Number": "将 INTx# 线关联到 IRQ 号",
    "Autonomous Reset Generation": "自主复位生成",
    "Background": "背景",
    "Bad Nak": "错误 Nak",
    "Baseline Error Detection and Handling": "基线错误检测与处理",
    "Basic Elements": "基本要素",
    "Basics of MSI Configuration": "MSI 配置基础",
    "Behavior During FLR": "FLR 期间的行为",
    "Bit Tracer": "位追踪器",
    "Block Type Detection": "块类型检测",
    "Bringing it all together": "综合概述",
    "Byte Enable Rules": "字节使能规则",
    "Byte Striping x8 Example": "字节条带化 x8 示例",
    "CRC": "CRC",
    "Card Removal Procedure": "卡移除流程",
    "Card Removal and Insertion Procedures": "卡移除与插入规程",
    "Changes for PCIe Spec Rev 2.1": "PCIe 规范 Rev 2.1 的变更",
    "Chapter 13: Physical Layer - Electrical": "第13章：物理层 - 电气",
    "Chapter 13: Physical Layer — Transmitter and Receiver": "第13章：物理层 — 发送器和接收器",
    "Chapter 14: Link Initialization & Training": "第14章：链路初始化和训练",
    "Chapter 14: Link Training and Status State Machine (LTSSM)": "第14章：链路训练和状态机（LTSSM）",
    "Chapter 15: Error Handling": "第15章：错误处理",
    "Chapter 16: Power Management": "第16章：电源管理",
    "Chapter 17: Interrupts": "第17章：中断",
    "Chapter 18: Reset": "第18章：复位",
    "Chapter 19: Hot Plug and Power Budgeting": "第19章：热插拔和功率预算",
    "Chapter 20: Multicast, TPH, and Resizable BAR": "第20章：多播、TPH 和可调整大小 BAR",
    "Chapter 4: Address Space & Transaction Routing": "第4章：地址空间和事务路由",
    "Chapter : Appendix B: Markets & Applications for PCI": "附录 B：PCI 市场与应用",
    "Chapter : Appendix C: Implementing Intelligent Adapt-": "附录 C：实现智能适配器",
    "Chapter : Appendix C: Implementing Intelligent Adapters in PCI and PCI Express Systems": "附录 C：在 PCI 和 PCI Express 系统中实现智能适配器",
    "Clock Requirements": "时钟要求",
    "Code Violation and Disparity Error Detection": "码违例和失衡错误检测",
    "Component Interfaces": "组件接口",
    "Conclusion": "结论",
    "Configuration State — General": "配置状态 — 概述",
    "Configuration.Complete": "Configuration.Complete",
    "Configuration.Lanenum.Wait": "Configuration.Lanenum.Wait",
    "Configuration.Linkwidth.Accept": "Configuration.Linkwidth.Accept",
    "Configuration.Linkwidth.Start": "Configuration.Linkwidth.Start",
    "Confirming Link and Lane Numbers.": "确认链路和通道编号",
    "Congestion Avoidance": "拥塞避免",
    "Continuous-Time Linear Equalization (CTLE)": "连续时间线性均衡（CTLE）",
    "Control Register": "控制寄存器",
    "Conventional Reset": "传统复位",
    "Current Link Speed[3:0]:": "当前链路速度 [3:0]：",
    "Cut-Through Operation": "直通模式操作",
    "D2 State—Deep Sleep": "D2 状态—深度休眠",
    "DLLP CRC Check": "DLLP CRC 检查",
    "DPA (Dynamic Power Allocation)": "DPA（动态功率分配）",
    "Data Link Layer Errors": "数据链路层错误",
    "Data Poisoning": "数据毒化",
    "Data Returned For Read Requests:": "读请求返回的数据：",
    "Data Stream and Data Blocks": "数据流和数据块",
    "De-skew Opportunities": "去偏斜时机",
    "Deadlock Avoidance": "死锁避免",
    "Decision Feedback Equalization (DFE)": "决策反馈均衡（DFE）",
    "Definition of Device Context": "设备上下文定义",
    "Descrambler": "解扰器",
    "Deserializer": "解串器",
    "Designing Devices with Links that can be Merged": "设计具有可合并链路的设备",
    "Detailed Configuration Substates": "详细配置子状态",
    "Detailed Polling Substates": "详细轮询子状态",
    "Detect.Quiet": "Detect.Quiet",
    "Determining INTx# Pin Support": "确定 INTx# 引脚支持",
    "Device INTx# Pins": "设备 INTx# 引脚",
    "Device-Class-Specific PM Specs": "设备类别特定电源管理规范",
    "Differences between PCI and PCIe Hot Plug": "PCI 和 PCIe 热插拔的区别",
    "Differential Receiver": "差分接收器",
    "Disparity Calculator": "失衡计算器",
    "Disparity Errors.": "失衡错误",
    "Downstream Component Decides to Enter L1 ASPM": "下游组件决定进入 L1 ASPM",
    "During Configuration.Complete": "在 Configuration.Complete 期间",
    "During Configuration.Idle": "在 Configuration.Idle 期间",
    "During Configuration.Lanenum.Accept": "在 Configuration.Lanenum.Accept 期间",
    "During Configuration.Lanenum.Wait": "在 Configuration.Lanenum.Wait 期间",
    "During Configuration.Linkwidth.Accept": "在 Configuration.Linkwidth.Accept 期间",
    "During Configuration.Linkwidth.Start": "在 Configuration.Linkwidth.Start 期间",
    "During Disable": "在 Disable 期间",
    "During Polling.Active": "在 Polling.Active 期间",
    "During Polling.Compliance:": "在 Polling.Compliance 期间：",
    "During Polling.Configuration": "在 Polling.Configuration 期间",
    "During Recovery.RcvrLock": "在 Recovery.RcvrLock 期间",
    "Dynamic Link Speed Changes": "动态链路速度变化",
    "ESD and Short Circuit Requirements": "ESD 和短路要求",
    "Effects of Jitter": "抖动的影响",
    "Electrical Idle": "电气空闲",
    "Elements Required to Support Hot Plug": "支持热插拔所需的要素",
    "Encoding Procedure": "编码过程",
    "Endpoints": "端点",
    "Entering Polling.Compliance:": "进入 Polling.Compliance：",
    "Equalization Notes": "均衡说明",
    "Error Checks by Layer": "按层级划分的错误检查",
    "Error Pollution": "错误传播",
    "Error Situations Handled by Ack/Nak": "Ack/Nak 处理的错误情况",
    "Example Flow of Software Error Investigation": "软件错误调查的示例流程",
    "Example of Cut-Through Operation": "直通模式操作示例",
    "Example: Implementing Host Failover in a PCI Express System": "示例：在 PCI Express 系统中实现主机故障切换",
    "Example: Implementing Intelligent Adapters in a PCI Express Base System": "示例：在 PCI Express 基础系统中实现智能适配器",
    "Exerciser Card": "练习卡",
    "Exit from L0s State": "退出 L0s 状态",
    "Exit from L1 ASPM State": "退出 L1 ASPM 状态",
    'Exit to "Configuration State"': '退出到 "Configuration 状态"',
    'Exit to "Configuration.Complete"': '退出到 "Configuration.Complete"',
    'Exit to "Configuration.Idle"': '退出到 "Configuration.Idle"',
    'Exit to "Configuration.Lanenum.Accept"': '退出到 "Configuration.Lanenum.Accept"',
    'Exit to "Configuration.Lanenum.Wait"': '退出到 "Configuration.Lanenum.Wait"',
    'Exit to "Configuration.Linkwidth.Start"': '退出到 "Configuration.Linkwidth.Start"',
    'Exit to "Detailed Recovery Substates"': '退出到 "Detailed Recovery Substates"',
    'Exit to "Detect State"': '退出到 "Detect 状态"',
    'Exit to "Detect.Quiet"': '退出到 "Detect.Quiet"',
    'Exit to "Disable State"': '退出到 "Disable 状态"',
    'Exit to "Hot Reset State"': '退出到 "Hot Reset 状态"',
    'Exit to "L0 State"': '退出到 "L0 状态"',
    'Exit to "L1.Idle"': '退出到 "L1.Idle"',
    'Exit to "L2.TransmitWake"': '退出到 "L2.TransmitWake"',
    'Exit to "Loopback State"': '退出到 "Loopback 状态"',
    'Exit to "Loopback.Active"': '退出到 "Loopback.Active"',
    'Exit to "Loopback.Exit"': '退出到 "Loopback.Exit"',
    'Exit to "Phase 1 Upstream"': '退出到 "Phase 1 Upstream"',
    'Exit to "Polling State"': '退出到 "Polling 状态"',
    'Exit to "Polling.Active"': '退出到 "Polling.Active"',
    'Exit to "Recovery State"': '退出到 "Recovery 状态"',
    'Exit to "Recovery.Idle"': '退出到 "Recovery.Idle"',
    'Exit to "Recovery.RcvrCfg"': '退出到 "Recovery.RcvrCfg"',
    'Exit to "Recovery.Speed"': '退出到 "Recovery.Speed"',
    'Exit to "Rx_L0s.FTS"': '退出到 "Rx_L0s.FTS"',
    'Exit to "L0 State" / 退出至"L0状态"': '退出到 "L0 状态"',
    'Exit to "Polling.Active"': '退出到 "Polling.Active"',
    'Exiting the L1 State': '退出 L1 状态',
    "Expansion Device Limits Power Consumption": "扩展设备限制功耗",
    "Fatal Uncorrectable Errors": "致命不可纠正错误",
    "Flow Control Credit Tracking": "流控信用跟踪",
    "Flow Control DLLP Format": "流控 DLLP 格式",
    "Framing Tokens": "成帧令牌",
    "Full-Swing Differential Voltage": "全摆幅差分电压",
    "Function Level Reset (FLR)": "功能级复位（FLR）",
    "Gen3 Physical Layer Receive Logic": "Gen3 物理层接收逻辑",
    "Gen3 Physical Layer Transmit Logic": "Gen3 物理层发送逻辑",
    "General": "概述",
    "General Rules": "通用规则",
    "Goal: Reliable TLP Transport": "目标：可靠的 TLP 传输",
    "Group Arbitration": "组仲裁",
    "Guidelines Regarding LTR Use": "LTR 使用指南",
    "Hardware Fixed Arbitration Scheme": "硬件固定仲裁方案",
    "Hardware-Fixed Arbitration": "硬件固定仲裁",
    "High Speed Signaling": "高速信令",
    "Higher-bandwidth PCI": "更高带宽 PCI",
    "Host Failover": "主机故障切换",
    "Hot Plug in the PCI Express Environment": "PCI Express 环境中的热插拔",
    "Hot Reset (In-band Reset)": "热复位（带内复位）",
    "Hot-Plug Considerations": "热插拔考虑因素",
    "How Errors are Reported": "错误如何报告",
    "How Timing is Enforced": "时序如何执行",
    "IDO (ID-based Ordering)": "IDO（基于 ID 的排序）",
    "INTx Collapsing": "INTx 合并",
    "INTx Delivery Rules": "INTx 传递规则",
    "Initiating the Recovery Process": "启动恢复过程",
    "Intelligent Adapters": "智能适配器",
    "Internal Error Reporting": "内部错误报告",
    "Interrupt Support Background": "中断支持背景",
    "Introduction": "引言",
    "Introduction to Gen3": "Gen3 简介",
    "Introduction to Link Power Management": "链路电源管理简介",
    "Isochronous Broker": "等时代理",
    "Isochronous Support": "等时支持",
    "Jitter, Noise, and Signal Attenuation": "抖动、噪声与信号衰减",
    "L0 State": "L0 状态",
    "L0s State": "L0s 状态",
    "L0s Transmitter State Machine": "L0s 发送器状态机",
    "L1 State": "L1 状态",
    "L1.Entry": "L1.Entry",
    "L2.Idle": "L2.Idle",
    "L2.TransmitWake": "L2.TransmitWake",
    "LCRC Error Check": "LCRC 错误检查",
    "LCRC Generator": "LCRC 生成器",
    "LTR Messages": "LTR 消息",
    "Lane Number Negotiation.": "通道编号协商",
    "Lane-to-Lane Skew": "通道间偏斜",
    "Large Link-Width Packet Format Rules": "大链路宽度数据包格式规则",
    "Legacy PCI Interrupt Delivery": "传统 PCI 中断传递",
    "Link Capabilities 2 Register": "链路能力 2 寄存器",
    "Link Configuration Example 2": "链路配置示例 2",
    "Link Configuration Example 3: Failed Lane": "链路配置示例 3：通道失效",
    "Link Control Register": "链路控制寄存器",
    "Link Disable": "链路禁用",
    "Link Number Negotiation.": "链路编号协商",
    "Link Training and Initialization": "链路训练和初始化",
    "Link Training[11]": "链路训练 [11]",
    "Link Wakeup from L2 Low Power State": "链路从 L2 低功耗状态唤醒",
    "Link Width Change": "链路宽度变化",
    "Loading the Port Arbitration Tables": "加载端口仲裁表",
    "Logic Analyzer": "逻辑分析仪",
    "Logical Idle": "逻辑空闲",
    "Loopback State": "环回状态",
    "Loopback.Entry": "Loopback.Entry",
    "MC Block All": "MC 全部阻止",
    "MC Block Untranslated": "MC 阻止未翻译",
    "MC Overlay BAR": "MC 覆盖 BAR",
    "MC Receive": "MC 接收",
    "MSI May Result In Errors": "MSI 可能导致错误",
    "Malformed TLP": "格式错误 TLP",
    "Manually Operated Retention Latch and Sensor": "手动操作的保持锁存器和传感器",
    "Mapping and Collapsing INTx Messages": "映射和合并 INTx 消息",
    "Max Link Speed [3:0]": "最大链路速度 [3:0]",
    "Memory Synchronization When Interrupt Handler Entered": "进入中断处理程序时的内存同步",
    "Message Address Register": "消息地址寄存器",
    "Message Data Register": "消息数据寄存器",
    "Message Requests": "消息请求",
    "Miscellaneous Transmit Topics": "杂项发送主题",
    "Motivation": "动机",
    "Multi-Root (MR) PCIe Switch Solution": "多根（MR）PCIe 交换机解决方案",
    "Multicast Capability": "多播能力",
    "Multicast Control": "多播控制",
    "Multiple Messages": "多消息",
    "Multiplexer": "多路选择器",
    "Mux and Control Logic": "多路选择器和控制逻辑",
    "Mux for Sync Header Bits": "同步头位多路选择器",
    "NEXT_TRANSMIT_SEQ Counter": "NEXT_TRANSMIT_SEQ 计数器",
    "Negotiated Link Width[9:4]": "协商链路宽度 [9:4]",
    "Next Capability Pointer": "下一个能力指针",
    "OBFF Message Rules": "OBFF 消息规则",
    "Observation": "观察",
    "On and Off States": "开启和关闭状态",
    "One Solution": "一种解决方案",
    "Ordered Set Example - SOS": "有序集示例 - SOS",
    "Ordered Sets": "有序集",
    "Ordered sets": "有序集",
    "Ordered sets Help De-Skewing": "有序集辅助去偏斜",
    "Ordering Rules Based On Packet Type": "基于数据包类型的排序规则",
    "Ordering Rules and Traffic Classes (TCs)": "排序规则和流量类别（TC）",
    "Other characteristics of the D2 state include:": "D2 状态的其他特性包括：",
    "Overlay Example": "覆盖示例",
    "Overview": "概述",
    "Overview of LTSSM States": "LTSSM 状态概述",
    "PCI Bus Initiator and Target": "PCI 总线发起方和目标",
    "PCI Express 3.0 Technology": "PCI Express 3.0 技术",
    "PCI Express Bus Driver Accesses PM Registers": "PCI Express 总线驱动访问电源管理寄存器",
    "PCI Express RTL Bus Monitor": "PCI Express RTL 总线监视器",
    "PCI Express Technology": "PCI Express 技术",
    "PCIe Error Checking Mechanisms": "PCIe 错误检查机制",
    "PCIe Error Definitions": "PCIe 错误定义",
    "PERST# Fundamental Reset Generation": "PERST# 基础复位生成",
    "PM Control and Status Register (PMCSR)": "电源管理控制和状态寄存器（PMCSR）",
    "Packet Filtering": "数据包过滤",
    "Packet Format Rules": "数据包格式规则",
    "Part Five: Additional System Topics": "第五部分：附加系统主题",
    "Pausing a Driver (Optional)": "暂停驱动（可选）",
    "Pending Bit Array": "待处理位阵列",
    "Performance Improvements": "性能改进",
    "Phase 3": "阶段 3",
    "Polling.Active": "Polling.Active",
    "Polling.Configuration": "Polling.Configuration",
    "Port Arbitration": "端口仲裁",
    "Port Arbitration Mechanisms": "端口仲裁机制",
    "Power Indicator": "电源指示灯",
    "Power Management": "电源管理",
    "Power Management Improvements": "电源管理改进",
    "Power Management Primer": "电源管理入门",
    "Pre-Silicon": "硅前",
    "Pre-shoot, De-emphasis, and Boost": "预冲、去加重和增强",
    "Previous Chapter": "上一章",
    "Properties of 10-bit Symbols": "10 位符号的属性",
    "Protocol Analyzer": "协议分析仪",
    "Quiescing a Driver That Controls Multiple Devices": "暂停控制多个设备的驱动",
    "Quiescing a Failed Card": "暂停故障卡",
    "REPLAY_TIMER Count": "REPLAY_TIMER 计数",
    "RTL Simulation Perspective": "RTL 仿真视角",
    "RTL vector export to PETracer Application": "RTL 向量导出到 PETracer 应用",
    "Reasons for Entering Recovery State": "进入恢复状态的原因",
    "Receive Buffer (Rx Buffer)": "接收缓冲器（Rx 缓冲器）",
    "Receiver DC Common Mode Voltage": "接收器 DC 共模电压",
    "Receiver Elements": "接收器要素",
    "Receiver Entry to Electrical Idle": "接收器进入电气空闲",
    "Receiver Exit from Electrical Idle": "接收器退出电气空闲",
    "Receiver Framing Requirements": "接收器组帧要求",
    "Receiver Lane-to-Lane De-skew Capability": "接收器通道间去偏斜能力",
    "Receiver handling of DLLPs": "接收器处理 DLLP",
    "Recovery from Framing Errors": "从组帧错误恢复",
    "Recovery.RcvrCfg": "Recovery.RcvrCfg",
    "Recovery.Speed": "Recovery.Speed",
    "Refclk Overview": "Refclk 概述",
    "Regaining Bit Lock": "重新获取位锁定",
    "Relaxed Ordering": "宽松排序",
    "Reset Exit": "复位退出",
    "Response of Data Link Layer to Receiver Error": "数据链路层对接收器错误的响应",
    "Retrain Link": "重新训练链路",
    "Root Complex Error Tracking and Reporting": "根复合体错误跟踪和报告",
    "Root's Response to Error Message": "根复合体对错误消息的响应",
    "Rx_L0s.Entry.": "Rx_L0s.Entry",
    "Rx_L0s.FTS.": "Rx_L0s.FTS",
    "SSC (Spread Spectrum Clocking)": "SSC（扩频时钟）",
    "Scenario 3: Downstream Component Receives TLP During Negotiation": "场景 3：下游组件在协商期间接收 TLP",
    "Scenario 4: Upstream Component Receives TLP During Negotiation": "场景 4：上游组件在协商期间接收 TLP",
    "Scenario 5: Upstream Component Rejects L1 Request": "场景 5：上游组件拒绝 L1 请求",
    "Scrambler": "扰码器",
    "Serializer": "串行器",
    "Setting up the Virtual Channel Arbitration Table": "设置虚拟通道仲裁表",
    "Slot Control": "插槽控制",
    "Slot Numbering Identification": "插槽编号标识",
    "Slot Power Limit Control": "插槽功率限制控制",
    "Software Can Disable the Link": "软件可以禁用链路",
    "Software User Interface": "软件用户界面",
    "Some MSI Rules and Recommendations": "一些 MSI 规则和建议",
    "Some Scrambler implementation rules:": "一些扰码器实现规则：",
    "Sources of PCI Express Errors": "PCI Express 错误源",
    "Spec requirements:": "规范要求：",
    "Special Consideration for Base System Peripherals": "基础系统外设的特殊考虑",
    "Split Transaction Errors": "拆分事务错误",
    "Split-Transaction Model": "拆分事务模型",
    "Standard Hot Plug Controller Signaling Interface": "标准热插拔控制器信令接口",
    "Standard User Interface": "标准用户界面",
    "Standardized Usage Model": "标准化使用模型",
    "Steering Tags": "导向标签",
    "Stressed-Eye Testing": "压力眼图测试",
    "Surprise Removal Notification": "意外移除通知",
    "Switch Arbitration Example": "交换机仲裁示例",
    "Switches": "交换机",
    "System Redundancy Improvement: Multi-casting": "系统冗余改进：多播",
    "TLP LCRC Check": "TLP LCRC 检查",
    "TPH (TLP Processing Hints)": "TPH（TLP 处理提示）",
    "TS1 and TS2 Ordered Sets": "TS1 和 TS2 有序集",
    "The Eye Test": "眼图测试",
    "The FC Initialization Sequence": "FC 初始化序列",
    "The History Multi-Processor Implementations Using PCI": "使用 PCI 的多处理器实现历史",
    "The Hot-Plug Controller Programming Interface": "热插拔控制器编程接口",
    "The MSI Model": "MSI 模型",
    "The MSI-X Model": "MSI-X 模型",
    "The Next Chapter": "下一章",
    "The PME Context": "PME 上下文",
    "The PME Sequence": "PME 序列",
    "The Power Budget Capabilities Register Set": "功率预算能力寄存器集",
    "The Power Budget Manager": "功率预算管理器",
    "The Power Budgeting Elements": "功率预算要素",
    "The Previous Chapter": "上一章",
    "The Problem": "问题",
    "The Solution": "解决方案",
    "The user interface includes the following features:": "用户界面包括以下特性：",
    "This Chapter": "本章",
    "Three-Tap Tx Equalizer Required": "需要三抽头发送器均衡器",
    "Time-Based, Weighted Round Robin Arbitration (TBWRR)": "基于时间的加权轮询仲裁（TBWRR）",
    "Timing Differences for Newer Spec Versions": "较新规范版本的时序差异",
    "Timing is Everything": "时序至关重要",
    "Traffic Class (TC)": "流量类（TC）",
    "Traffic Classes Must Match": "流量类别必须匹配",
    "Transaction Layer": "事务层",
    "Transaction Ordering": "事务排序",
    "Transmission Loss": "传输损耗",
    "Transmit Clock (Tx Clock)": "发送时钟（Tx 时钟）",
    "Transmit Logic Details (Gen1 and Gen2 Only)": "发送逻辑细节（仅 Gen1 和 Gen2）",
    "Transmitter DLLP Handling": "发送器 DLLP 处理",
    "Transmitter Driver Characteristics": "发送器驱动特性",
    "Transmitter Elements": "发送器要素",
    "Transmitter Entry to Electrical Idle": "发送器进入电气空闲",
    "Transmitter Exit from Electrical Idle": "发送器退出电气空闲",
    "Transmitter Framing Requirements": "发送器组帧要求",
    "Transmitter SOS Rules": "发送器 SOS 规则",
    "Transmitter Voltages": "发送器电压",
    "Transmitter's Response to a Nak": "发送器对 Nak 的响应",
    "Transmitter's Response to an Ack DLLP": "发送器对 Ack DLLP 的响应",
    "Turning Slot On": "开启插槽",
    "Tx Buffer": "Tx 缓冲器",
    "Tx_L0s.FTS.": "Tx_L0s.FTS",
    "Uncorrectable Error Masking": "不可纠正错误屏蔽",
    "Uncorrectable Errors": "不可纠正错误",
    "Undefined[10]": "未定义 [10]",
    "Unexpected Completion": "意外完成",
    "Unlock Message Rules": "解锁消息规则",
    "Unsupported Request (UR) Status": "不支持请求（UR）状态",
    "Unused Base and Limit Registers": "未使用基址和限制寄存器",
    "Upstream Component Response to L1 ASPM Request.": "上游组件对 L1 ASPM 请求的响应",
    "Upstream Lanes": "上游通道",
    "Upstream Lanes.": "上游通道",
    "VC Buffers Offer an Advantage": "VC 缓冲器的优势",
    "Variables:": "变量：",
    "Vendor-Specific DLLP Format": "厂商特定 DLLP 格式",
    "Virtual INTx Signaling": "虚拟 INTx 信令",
    "Virtual INTx Wire Delivery": "虚拟 INTx 线传递",
    "Voltage Margining": "电压裕量调节",
    "Waking Non-Communicating Links": "唤醒非通信链路",
    "Weighted Round Robin Arbitration Scheme": "加权轮询仲裁方案",
    "When a Fundamental Reset occurs:": "当发生基础复位时：",
    "When to use IDO": "何时使用 IDO",
    "x8 Packet Format Example": "x8 数据包格式示例",
    "– Transitioned to Electrical Idle": "转换到电气空闲",
    "• When an EDB is received:": "当收到 EDB 时：",
    "• When an EDS Token is received as the last DW of a Data Block:": "当 EDS 令牌作为数据块的最后一个 DW 收到时：",
}

# CN-only → add English
CN2EN = {
    "上一章": "The Previous Chapter",
    "下一个接收TLP的序列号": "Next Received TLP's Sequence Number",
    "主动状态电源管理(ASPM)": "Active State Power Management (ASPM)",
    "使故障卡静止（Quiescing）": "Quiescing a Failed Card",
    "动机": "Motivation",
    "卡片移除流程": "Card Removal Procedure",
    "卡移除与插入规程": "Card Removal and Insertion Procedures",
    "发送器组帧要求": "Transmitter Framing Requirements",
    "场景4：协商期间上游组件接收TLP": "Scenario 4: Upstream Component Receives TLP",
    "均衡电压": "Equalization Voltage",
    "均衡说明": "Equalization Notes",
    "基线错误检测与处理": "Baseline Error Detection and Handling",
    "多根(MR)PCIe交换机解决方案": "Multi-Root (MR) PCIe Switch Solution",
    "引言": "Introduction",
    "成帧令牌": "Framing Tokens",
    "抖动、噪声与信号衰减": "Jitter, Noise, and Signal Attenuation",
    "接收器特性": "Receiver Characteristics",
    "物理层概述": "Physical Layer Overview",
    "生产者/消费者序列 — 无错误": "Producer/Consumer Sequence — No Errors",
    "电压裕量调节": "Voltage Margining",
    "直通模式操作示例": "Example of Cut-Through Operation",
    "通道编号协商": "Lane Number Negotiation",
    "链路电源管理简介": "Introduction to Link Power Management",
    "链路编号协商": "Link Number Negotiation",
    "链路能力2寄存器": "Link Capabilities 2 Register",
    "问题": "Problem",
    "本章": "This Chapter",
    "前言": "Introduction",
    "概述": "Overview",
}


def fix_headings_in_text(text):
    """Fix all heading formats in a chunk text."""
    lines = text.split("\n")
    new_lines = []
    changed = False

    for line in lines:
        s = line.strip()
        if s.startswith("## ") and "## EN | ZH" not in s and not s.startswith("|"):
            heading = s[3:].strip()

            # Skip if already has | with Chinese
            if " | " in s and re.search(r'[一-鿿]', s):
                new_lines.append(line)
                continue

            # Check if it has / format (already converted but double-check)
            if " / " in s and re.search(r'[一-鿿]', s):
                # Convert / to |
                new_line = line.replace(" / ", " | ")
                new_lines.append(new_line)
                if new_line != line:
                    changed = True
                continue

            # EN-only heading
            if heading in EN2CN:
                new_line = f"## {heading} | {EN2CN[heading]}"
                new_lines.append(new_line)
                if new_line != line:
                    changed = True
                continue

            # CN-only heading - add English
            if heading in CN2EN:
                new_line = f"## {CN2EN[heading]} | {heading}"
                new_lines.append(new_line)
                if new_line != line:
                    changed = True
                continue

            new_lines.append(line)
        else:
            new_lines.append(line)

    return "\n".join(new_lines), changed


def main():
    fixed = 0
    for n in range(1, 1361):
        f = TEMP / f"output_chunk{n:04d}.md"
        if not f.exists():
            continue
        text = f.read_text(encoding="utf-8")
        new_text, changed = fix_headings_in_text(text)
        if changed:
            f.write_text(new_text, encoding="utf-8")
            fixed += 1

    print(f"Fixed headings in {fixed} chunks")
    print(f"Total unique EN→CN mappings: {len(EN2CN)}")
    print(f"Total unique CN→EN mappings: {len(CN2EN)}")


if __name__ == "__main__":
    main()
